package com.jianbox.app;

import android.app.Activity;
import android.app.AlertDialog;
import android.content.Context;
import android.content.Intent;
import android.net.Uri;
import android.os.Environment;
import android.os.Handler;
import android.os.Looper;
import android.view.Gravity;
import android.view.View;
import android.widget.FrameLayout;
import android.widget.ProgressBar;
import android.widget.TextView;
import android.widget.LinearLayout;
import android.widget.Toast;
import android.webkit.URLUtil;

/** Application-owned downloader facade; it never delegates transfer to DownloadManager. */
final class BrowserDownloads {
    static long enqueue(Context context,String url,String userAgent,String disposition,String mime){if(!BrowserUrlRules.isWebUrl(url)){Toast.makeText(context,BlobDownloads.isBlob(url)?"临时链接只能在原网页下载，请重新点击网页下载按钮":"此下载链接协议暂不支持",Toast.LENGTH_LONG).show();return -1;}try{String name=URLUtil.guessFileName(url,disposition,mime);DownloadStore.Record r=new DownloadStore.Record();r.url=url;r.name=name;r.mime=mime==null||mime.isEmpty()?"application/octet-stream":mime;r.userAgent=userAgent==null?"":userAgent;r.status=DownloadStore.QUEUED;DownloadStore.put(context,r);Intent i=new Intent(context,BrowserDownloadService.class).putExtra(BrowserDownloadService.EXTRA_ID,r.id);if(android.os.Build.VERSION.SDK_INT>=26)context.startForegroundService(i);else context.startService(i);Toast.makeText(context,"已加入简盒下载："+name,Toast.LENGTH_SHORT).show();return safeId(r.id);}catch(Exception e){Toast.makeText(context,"无法开始应用内下载，请检查链接或网络",Toast.LENGTH_LONG).show();return -1;}}
    private static long safeId(String id){return id.hashCode()&0x7fffffffL;}
    static void confirm(Context context,String url,String userAgent,String disposition,String mime){confirm(context,url,userAgent,disposition,mime,null);}
    static void confirm(Context context,String url,String userAgent,String disposition,String mime,FrameLayout overlayHost){if(!(context instanceof Activity)){enqueue(context,url,userAgent,disposition,mime);return;}String name=URLUtil.guessFileName(url,disposition,mime);LinearLayout summary=Ui.vertical(context);summary.setPadding(Ui.dp(context,16),Ui.dp(context,2),Ui.dp(context,16),Ui.dp(context,4));summary.addView(Ui.text(context,name,12,Ui.TEXT,true));TextView path=Ui.text(context,"保存到简盒应用目录\n"+destinationHint(context),9,Ui.MUTED,false);path.setPadding(0,Ui.dp(context,7),0,0);summary.addView(path);new AlertDialog.Builder(context).setTitle("确认下载").setView(summary).setNegativeButton("取消",null).setPositiveButton("开始下载",(d,w)->{long id=enqueue(context,url,userAgent,disposition,mime);if(id>0)showProgress((Activity)context,overlayHost,id,name);}).show();}
    static void openManager(Context context){context.startActivity(new Intent(context,DownloadActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));}
    static String destinationHint(Context context){JianData data=new JianData(context);FileHint f=new FileHint(context,"内部私密目录".equals(data.downloadLocation()));return f.path;}
    private static final class FileHint{String path;FileHint(Context c,boolean privateDir){java.io.File d=privateDir?new java.io.File(c.getFilesDir(),"downloads"):c.getExternalFilesDir(Environment.DIRECTORY_DOWNLOADS);path=d==null?new java.io.File(c.getFilesDir(),"downloads").getAbsolutePath():d.getAbsolutePath();}}
    static void showProgress(Activity activity,FrameLayout host,long numericId,String name){if(host==null){Toast.makeText(activity,"下载将在后台继续，可前往下载管理查看进度",Toast.LENGTH_LONG).show();return;}View old=host.findViewWithTag("browser_download_progress");if(old!=null)host.removeView(old);LinearLayout card=Ui.vertical(activity);card.setTag("browser_download_progress");card.setPadding(Ui.dp(activity,12),Ui.dp(activity,9),Ui.dp(activity,12),Ui.dp(activity,9));card.setBackground(Ui.bordered(0xFAFFFFFF,Ui.BORDER,11,activity));card.setElevation(Ui.dp(activity,14));LinearLayout head=Ui.horizontal(activity);TextView title=Ui.text(activity,name,10,Ui.TEXT,true);title.setSingleLine(true);head.addView(title,new LinearLayout.LayoutParams(0,Ui.dp(activity,24),1));TextView close=Ui.text(activity,"×",16,Ui.MUTED,true);close.setGravity(Gravity.CENTER);head.addView(close,new LinearLayout.LayoutParams(Ui.dp(activity,28),Ui.dp(activity,24)));card.addView(head);TextView detail=Ui.text(activity,"正在准备…",9,Ui.MUTED,false);card.addView(detail);ProgressBar progress=new ProgressBar(activity,null,android.R.attr.progressBarStyleHorizontal);progress.setMax(100);progress.setIndeterminate(true);progress.setProgressTintList(android.content.res.ColorStateList.valueOf(Ui.GREEN));card.addView(progress,new LinearLayout.LayoutParams(-1,Ui.dp(activity,5)));TextView manage=Ui.text(activity,"查看下载管理",9,Ui.GREEN,true);manage.setGravity(Gravity.END|Gravity.CENTER_VERTICAL);manage.setPadding(0,Ui.dp(activity,5),0,0);manage.setOnClickListener(v->openManager(activity));card.addView(manage,new LinearLayout.LayoutParams(-1,Ui.dp(activity,28)));FrameLayout.LayoutParams cp=new FrameLayout.LayoutParams(Ui.dp(activity,238),-2,Gravity.TOP|Gravity.END);cp.setMargins(Ui.dp(activity,8),Ui.dp(activity,52),Ui.dp(activity,8),0);host.addView(card,cp);card.setAlpha(0f);card.setTranslationY(-Ui.dp(activity,10));card.animate().alpha(1f).translationY(0f).setDuration(160).start();Handler handler=new Handler(Looper.getMainLooper());Runnable[] tick=new Runnable[1];close.setOnClickListener(v->{handler.removeCallbacks(tick[0]);if(card.getParent()==host)host.removeView(card);});tick[0]=()->{if(card.getParent()!=host||activity.isFinishing())return;DownloadStore.Record record=findByNumericId(activity,numericId);boolean terminal=false;if(record!=null){if(record.total>0){progress.setIndeterminate(false);progress.setProgress((int)Math.min(100,record.done*100/record.total));detail.setText(format(record.done)+" / "+format(record.total)+(record.speed>0?" · "+format(record.speed)+"/秒":""));}else detail.setText(record.status==DownloadStore.QUEUED?"排队中…":"正在连接…");if(record.status==DownloadStore.COMPLETE){progress.setIndeterminate(false);progress.setProgress(100);detail.setText("下载完成");manage.setText("打开下载管理");terminal=true;}else if(record.status==DownloadStore.FAILED){progress.setIndeterminate(false);detail.setText(record.error);terminal=true;}}if(!terminal)handler.postDelayed(tick[0],500);};handler.post(tick[0]);}
    private static DownloadStore.Record findByNumericId(Context c,long id){for(DownloadStore.Record r:DownloadStore.all(c))if(safeId(r.id)==id)return r;return null;}
    private static String format(long v){if(v<1024)return v+" B";if(v<1024*1024)return String.format(java.util.Locale.ROOT,"%.1f KB",v/1024f);return String.format(java.util.Locale.ROOT,"%.1f MB",v/1024f/1024f);}
    private BrowserDownloads(){}
}
