package com.jianbox.app;

import android.app.Activity;
import android.app.AlertDialog;
import android.graphics.Bitmap;
import android.graphics.Color;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.text.InputFilter;
import android.text.InputType;
import android.view.Gravity;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;

import org.json.JSONObject;

import java.util.Locale;
import java.util.regex.Pattern;

/** Three-step password recovery: email, recovery OTP, then new password. */
public class ResetPasswordActivity extends Activity {
    private static final long CODE_VALID_MS=10*60*1000L;
    private static final Pattern EMAIL=Pattern.compile("^[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,}$",Pattern.CASE_INSENSITIVE);
    private final Handler handler=new Handler(Looper.getMainLooper());
    private JianData data;private TextView status,stepLabel;private EditText email,code,password,confirm;private Button send,verify,save;
    private String pendingEmail="",recoveryToken="";private long sentAt;private int cooldown,failures;
    private final Runnable cooldownTick=new Runnable(){public void run(){if(cooldown<=0){if(send!=null){send.setEnabled(true);send.setText("重新发送验证码");}return;}if(send!=null)send.setText(String.format(Locale.CHINA,"%d 秒后可重发",cooldown--));handler.postDelayed(this,1000);}};

    @Override public void onCreate(Bundle state){super.onCreate(state);data=new JianData(this);Ui.applyTheme(data);if(UpdateGuard.enforce(this))return;build();}
    @Override protected void onResume(){super.onResume();UpdateGuard.resume(this);}
    private void build(){ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);if(Ui.GLASS)scroll.setBackground(ImageStore.background(this,data.appBackgroundPath(),0x26000000,0,0x22FFFFFF,100,0,data.appBackgroundPosition()));else scroll.setBackground(Ui.bg(Ui.GREEN_PALE,0,this));LinearLayout root=Ui.vertical(this);root.setPadding(Ui.dp(this,16),Ui.dp(this,14),Ui.dp(this,16),Ui.dp(this,28));int width=Math.min(getResources().getDisplayMetrics().widthPixels,Ui.dp(this,560));scroll.addView(root,new ScrollView.LayoutParams(width,-2,Gravity.CENTER_HORIZONTAL));
        LinearLayout header=Ui.horizontal(this);TextView back=Ui.text(this,"‹",27,Ui.TEXT,false);back.setGravity(Gravity.CENTER);back.setBackground(Ui.bordered(Ui.SURFACE,Ui.BORDER,11,this));back.setOnClickListener(v->finish());header.addView(back,Ui.lp(Ui.dp(this,40),Ui.dp(this,40)));LinearLayout heading=Ui.vertical(this);heading.setPadding(Ui.dp(this,11),0,0,0);heading.addView(Ui.label(this,"JIAN BOX · RECOVERY"));heading.addView(Ui.text(this,"找回密码",20,Ui.TEXT,true));header.addView(heading,new LinearLayout.LayoutParams(0,Ui.dp(this,46),1));TextView badge=Ui.text(this,"验证",9,Ui.GREEN,true);badge.setGravity(Gravity.CENTER);badge.setBackground(Ui.bg(Ui.GREEN_SOFT,10,this));header.addView(badge,Ui.lp(Ui.dp(this,48),Ui.dp(this,32)));root.addView(header,new LinearLayout.LayoutParams(-1,Ui.dp(this,52)));
        LinearLayout identity=Ui.card(this);LinearLayout row=Ui.horizontal(this);Bitmap avatar=ImageStore.load(data.profileAvatarPath());if(avatar!=null){ImageView image=new ImageView(this);image.setImageBitmap(avatar);image.setScaleType(ImageView.ScaleType.CENTER_CROP);image.setClipToOutline(true);image.setBackground(Ui.bg(Ui.GREEN_SOFT,18,this));row.addView(image,Ui.lp(Ui.dp(this,54),Ui.dp(this,54)));}else row.addView(Ui.icon(this,"钥",Color.WHITE),Ui.lp(Ui.dp(this,54),Ui.dp(this,54)));LinearLayout copy=Ui.vertical(this);copy.setPadding(Ui.dp(this,12),0,0,0);copy.addView(Ui.text(this,"通过邮箱重新设置密码",15,Ui.TEXT,true));copy.addView(Ui.text(this,"验证码校验通过前不会显示新密码输入框",10,Ui.MUTED,false));row.addView(copy,new LinearLayout.LayoutParams(0,Ui.dp(this,54),1));identity.addView(row);root.addView(identity,new LinearLayout.LayoutParams(-1,-2));Ui.margin(identity,0,0,0,10,this);
        LinearLayout card=Ui.card(this);LinearLayout title=Ui.horizontal(this);TextView glyph=Ui.text(this,"密",11,Color.WHITE,true);glyph.setGravity(Gravity.CENTER);glyph.setBackground(Ui.bg(Ui.GREEN,8,this));title.addView(glyph,Ui.lp(Ui.dp(this,26),Ui.dp(this,26)));stepLabel=Ui.text(this,"第 1 步 · 验证账号邮箱",15,Ui.TEXT,true);stepLabel.setPadding(Ui.dp(this,9),0,0,0);title.addView(stepLabel,new LinearLayout.LayoutParams(0,Ui.dp(this,30),1));card.addView(title);
        card.addView(label("邮箱"));email=field("name@example.com",InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_EMAIL_ADDRESS);card.addView(email);send=Ui.button(this,"发送找回验证码",true);card.addView(send,new LinearLayout.LayoutParams(-1,Ui.dp(this,44)));
        TextView codeLabel=label("恢复验证码");codeLabel.setTag("verify_step");codeLabel.setVisibility(View.GONE);card.addView(codeLabel);code=field("输入邮件中的数字验证码",InputType.TYPE_CLASS_NUMBER);code.setTag("verify_step");code.setFilters(new InputFilter[]{new InputFilter.LengthFilter(10)});code.setVisibility(View.GONE);card.addView(code);verify=Ui.button(this,"验证邮箱",true);verify.setTag("verify_step");verify.setVisibility(View.GONE);card.addView(verify,new LinearLayout.LayoutParams(-1,Ui.dp(this,44)));
        TextView passwordLabel=label("新密码");passwordLabel.setTag("password_step");passwordLabel.setVisibility(View.GONE);card.addView(passwordLabel);password=field("至少 8 位字符",InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);password.setTag("password_step");password.setVisibility(View.GONE);card.addView(password);TextView confirmLabel=label("确认新密码");confirmLabel.setTag("password_step");confirmLabel.setVisibility(View.GONE);card.addView(confirmLabel);confirm=field("再次输入新密码",InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);confirm.setTag("password_step");confirm.setVisibility(View.GONE);card.addView(confirm);save=Ui.button(this,"保存新密码",true);save.setTag("password_step");save.setVisibility(View.GONE);card.addView(save,new LinearLayout.LayoutParams(-1,Ui.dp(this,44)));
        status=Ui.text(this,"请输入注册时使用的邮箱",10,Ui.GREEN,true);status.setPadding(Ui.dp(this,10),Ui.dp(this,8),Ui.dp(this,10),Ui.dp(this,8));status.setBackground(Ui.bordered(Ui.SOFT_SURFACE,Ui.BORDER,9,this));card.addView(status);Ui.margin(status,0,9,0,0,this);TextView privacy=Ui.text(this,"已注册邮箱会收到验证码；未注册邮箱不会进入下一步。为保护账号隐私，服务端不会直接返回邮箱是否存在。",9,Ui.MUTED,false);privacy.setPadding(Ui.dp(this,2),Ui.dp(this,8),Ui.dp(this,2),0);card.addView(privacy);root.addView(card,new LinearLayout.LayoutParams(-1,-2));setContentView(scroll);send.setOnClickListener(v->sendRecovery());verify.setOnClickListener(v->verifyRecovery());save.setOnClickListener(v->savePassword());}
    private TextView label(String value){TextView v=Ui.text(this,value,10,Ui.MUTED,true);v.setPadding(Ui.dp(this,2),Ui.dp(this,9),0,Ui.dp(this,5));return v;}
    private EditText field(String hint,int type){EditText v=new EditText(this);v.setHint(hint);v.setSingleLine(true);v.setInputType(type);v.setTextSize(12);v.setTextColor(Ui.TEXT);v.setHintTextColor(Ui.MUTED);v.setBackground(Ui.bordered(Ui.SOFT_SURFACE,Ui.BORDER,10,this));v.setPadding(Ui.dp(this,12),0,Ui.dp(this,12),0);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,Ui.dp(this,45));lp.setMargins(0,0,0,Ui.dp(this,7));v.setLayoutParams(lp);return v;}
    private String validEmail(){String value=email.getText().toString().trim().toLowerCase(Locale.ROOT);if(!EMAIL.matcher(value).matches()){setStatus("请输入有效的邮箱地址",true);return null;}if(!BackendClient.configured()){setStatus("账号服务配置缺失，请安装完整构建版本",true);return null;}return value;}
    private void showTagged(String tag,boolean visible){LinearLayout card=(LinearLayout)status.getParent();for(int i=0;i<card.getChildCount();i++){View child=card.getChildAt(i);if(tag.equals(child.getTag()))child.setVisibility(visible?View.VISIBLE:View.GONE);}}
    private void sendRecovery(){String value=validEmail();if(value==null)return;if(cooldown>0){setStatus("请稍候再重新发送",true);return;}send.setEnabled(false);setStatus("正在请求找回验证码…",false);try{BackendClient.request("/auth/v1/recover","POST",new JSONObject().put("email",value),(ok,body,error)->{if(!ok){send.setEnabled(true);setStatus(error,true);return;}pendingEmail=value;sentAt=System.currentTimeMillis();failures=0;cooldown=60;showTagged("verify_step",true);verify.setEnabled(true);stepLabel.setText("第 2 步 · 输入恢复验证码");setStatus("请求已提交。已注册邮箱会收到验证码；未注册邮箱不会进入下一步，请检查收件箱和垃圾邮件",false);code.requestFocus();handler.removeCallbacks(cooldownTick);handler.post(cooldownTick);});}catch(Exception e){send.setEnabled(true);setStatus("找回请求格式错误",true);}}
    private void verifyRecovery(){String value=validEmail();if(value==null)return;if(!value.equals(pendingEmail)){setStatus("邮箱已改变，请重新发送验证码",true);return;}if(System.currentTimeMillis()-sentAt>CODE_VALID_MS){setStatus("验证码已过期，请重新发送",true);return;}if(failures>=5){setStatus("错误次数过多，请重新发送验证码",true);return;}String token=code.getText().toString().trim();if(!token.matches("\\d{6,10}")){setStatus("请输入邮件中的完整数字验证码（当前邮件为 8 位）",true);return;}verify.setEnabled(false);setStatus("正在验证邮箱…",false);try{BackendClient.request("/auth/v1/verify","POST",new JSONObject().put("email",value).put("token",token).put("type","recovery"),(ok,body,error)->{if(!ok){failures++;verify.setEnabled(failures<5);setStatus(failures>=5?"验证码连续错误 5 次，请重新发送":error+"（还可尝试 "+(5-failures)+" 次）",true);return;}recoveryToken=body==null?"":body.optString("access_token","");if(recoveryToken.isEmpty()){verify.setEnabled(true);setStatus("服务端未返回密码恢复会话，请重新验证",true);return;}email.setEnabled(false);send.setVisibility(View.GONE);showTagged("verify_step",false);showTagged("password_step",true);stepLabel.setText("第 3 步 · 设置新密码");setStatus("邮箱验证成功，现在可以设置新密码",false);password.requestFocus();});}catch(Exception e){verify.setEnabled(true);setStatus("验证码校验请求失败，可重新点击验证",true);}}
    private void savePassword(){String first=password.getText().toString(),second=confirm.getText().toString();if(recoveryToken.isEmpty()){setStatus("请先完成邮箱验证码验证",true);return;}if(first.length()<8){setStatus("新密码至少需要 8 位",true);return;}if(!first.equals(second)){setStatus("两次输入的新密码不一致",true);return;}save.setEnabled(false);setStatus("正在安全更新密码…",false);try{BackendClient.request("/auth/v1/user","PUT",new JSONObject().put("password",first),recoveryToken,(ok,body,error)->{if(!ok){save.setEnabled(true);setStatus(error,true);return;}recoveryToken="";new AlertDialog.Builder(this).setTitle("密码修改成功").setMessage("新密码已生效，请返回账号页重新登录。").setCancelable(false).setPositiveButton("返回登录",(d,w)->finish()).show();setStatus("密码修改成功",false);password.setText("");confirm.setText("");});}catch(Exception e){save.setEnabled(true);setStatus("密码更新请求失败",true);}}
    private void setStatus(String message,boolean error){status.setText(message);status.setTextColor(error?Ui.RED:Ui.GREEN);}
    @Override protected void onDestroy(){handler.removeCallbacks(cooldownTick);super.onDestroy();}
}
