create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  is_admin boolean not null default false,
  created_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

alter table public.profiles add column if not exists is_admin boolean not null default false;

create table if not exists public.app_updates (
  id bigint generated by default as identity primary key,
  version_code integer not null,
  version_name text not null,
  min_version_code integer not null default 1,
  apk_url text not null default '',
  notes text not null default '',
  is_published boolean not null default false,
  force_update boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.app_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  event_name text not null,
  app_version integer,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.app_updates enable row level security;
alter table public.app_events enable row level security;

-- Data API privileges are deliberately narrower than table ownership. RLS
-- limits rows; these grants also prevent a client from changing is_admin.
grant usage on schema public to anon, authenticated;
revoke all on public.profiles from anon, authenticated;
revoke all on public.app_updates from anon, authenticated;
revoke all on public.app_events from anon, authenticated;
grant select on public.app_updates to anon, authenticated;
grant select on public.profiles to authenticated;
grant update (display_name, last_seen_at) on public.profiles to authenticated;
grant insert on public.app_events to authenticated;
grant usage, select on sequence public.app_events_id_seq to authenticated;

create policy "profile owner read" on public.profiles for select to authenticated
  using ((select auth.uid()) = id);
create policy "profile owner update" on public.profiles for update
  to authenticated
  using ((select auth.uid()) = id)
  with check ((select auth.uid()) = id);
create policy "published updates are public" on public.app_updates for select to anon, authenticated
  using (is_published = true);
create policy "user can write own events" on public.app_events for insert to authenticated
  with check ((select auth.uid()) = user_id);

create index if not exists profiles_last_seen_at_idx on public.profiles (last_seen_at);
create index if not exists app_events_user_created_at_idx on public.app_events (user_id, created_at desc);
create index if not exists app_updates_published_version_idx on public.app_updates (version_code desc)
  where is_published = true;

-- Dashboard-only statistics. Grant administrator access intentionally after the
-- first account is created; this never exposes a service_role key to the APK.
create or replace function public.jianbox_metrics()
returns table (registered_users bigint, active_24h bigint, active_30d bigint)
language sql stable security definer set search_path = public as $$
  select
    (select count(*) from public.profiles),
    (select count(*) from public.profiles where last_seen_at >= now() - interval '24 hours'),
    (select count(*) from public.profiles where last_seen_at >= now() - interval '30 days');
$$;

revoke all on function public.jianbox_metrics() from public, anon, authenticated;

create or replace function public.jianbox_is_admin()
returns boolean language sql stable security definer set search_path = public as $$
  select coalesce((select is_admin from public.profiles where id = auth.uid()), false);
$$;

revoke all on function public.jianbox_is_admin() from public, anon, authenticated;

create or replace function public.jianbox_admin_metrics()
returns table (registered_users bigint, active_24h bigint, active_30d bigint)
language plpgsql stable security definer set search_path = public as $$
begin
  if not public.jianbox_is_admin() then raise exception 'administrator required'; end if;
  return query select * from public.jianbox_metrics();
end;
$$;

revoke all on function public.jianbox_admin_metrics() from public, anon;
grant execute on function public.jianbox_admin_metrics() to authenticated;

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, display_name) values (new.id, coalesce(new.raw_user_meta_data->>'display_name', split_part(new.email, '@', 1))) on conflict (id) do nothing;
  return new;
end;
$$;

revoke all on function public.handle_new_user() from public, anon, authenticated;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

-- A signed-in user may update their own display metadata and last_seen_at, but
-- must never be able to promote themselves to administrator through PostgREST.
create or replace function public.protect_profile_admin()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if new.is_admin is distinct from old.is_admin then
    raise exception 'is_admin may only be changed by a trusted administrator workflow';
  end if;
  return new;
end;
$$;

revoke all on function public.protect_profile_admin() from public, anon, authenticated;
drop trigger if exists protect_profile_admin_changes on public.profiles;
create trigger protect_profile_admin_changes before update on public.profiles
for each row execute procedure public.protect_profile_admin();
