-- Admin Console and privacy-preserving installation metrics.
-- Run after migrations 001 through 005. This never stores an email for an
-- anonymous installation; installation_id is a random UUID generated on-device.

alter table public.profiles add column if not exists installation_id uuid;

create table if not exists public.anonymous_installs (
  installation_id uuid primary key,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  last_app_version integer
);

alter table public.anonymous_installs enable row level security;
revoke all on public.anonymous_installs from anon, authenticated;

create or replace function public.jianbox_record_install(p_installation uuid, p_app_version integer)
returns void
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
begin
  if p_installation is null then raise exception 'installation id required'; end if;
  insert into public.anonymous_installs (installation_id, last_app_version)
  values (p_installation, p_app_version)
  on conflict (installation_id) do update
    set last_seen_at = now(), last_app_version = excluded.last_app_version;
end;
$$;

create or replace function public.jianbox_bind_installation(p_installation uuid)
returns void
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
begin
  if auth.uid() is null then raise exception 'authentication required'; end if;
  if p_installation is null then raise exception 'installation id required'; end if;
  update public.profiles set installation_id = p_installation where id = auth.uid();
end;
$$;

revoke all on function public.jianbox_record_install(uuid, integer) from public;
grant execute on function public.jianbox_record_install(uuid, integer) to anon, authenticated;
revoke all on function public.jianbox_bind_installation(uuid) from public, anon;
grant execute on function public.jianbox_bind_installation(uuid) to authenticated;

create index if not exists anonymous_installs_last_seen_at_idx
  on public.anonymous_installs (last_seen_at desc);

-- The metrics function remains callable only by the checked administrator RPC.
-- The old version returns three columns, so it must be replaced rather than
-- CREATE OR REPLACE with an incompatible return signature.
drop function if exists public.jianbox_admin_metrics();
create function public.jianbox_admin_metrics()
returns table (
  registered_users bigint,
  active_24h bigint,
  active_30d bigint,
  anonymous_active_30d bigint,
  anonymous_current bigint
)
language plpgsql
stable
security definer
set search_path = pg_catalog, public
as $$
begin
  if not public.jianbox_is_admin() then raise exception 'administrator required'; end if;
  return query select
    (select count(*) from public.profiles),
    (select count(*) from public.profiles where last_seen_at >= now() - interval '24 hours'),
    (select count(*) from public.profiles where last_seen_at >= now() - interval '30 days'),
    (select count(*) from public.anonymous_installs a where a.last_seen_at >= now() - interval '30 days' and not exists (select 1 from public.profiles p where p.installation_id = a.installation_id)),
    (select count(*) from public.anonymous_installs a where not exists (select 1 from public.profiles p where p.installation_id = a.installation_id));
end;
$$;

revoke all on function public.jianbox_admin_metrics() from public, anon;
grant execute on function public.jianbox_admin_metrics() to authenticated;

create table if not exists public.admin_audit_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid references public.profiles(id) on delete set null,
  target_user_id uuid,
  action text not null check (action in ('ban', 'unban', 'delete')),
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
alter table public.admin_audit_logs enable row level security;
revoke all on public.admin_audit_logs from anon, authenticated;
create index if not exists admin_audit_logs_created_at_idx on public.admin_audit_logs (created_at desc);
