-- Release console, announcements, APK storage, and expanded audit logging.

create schema if not exists private;
revoke all on schema private from public, anon;
grant usage on schema private to authenticated;

create or replace function private.jianbox_is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.profiles
    where id = (select auth.uid())
      and is_admin = true
  );
$$;

revoke all on function private.jianbox_is_admin() from public, anon, authenticated;
grant execute on function private.jianbox_is_admin() to authenticated;

alter table public.app_updates add column if not exists channel text not null default 'stable';
alter table public.app_updates add column if not exists rollout_percent smallint not null default 100;
alter table public.app_updates add column if not exists file_name text;
alter table public.app_updates add column if not exists file_size bigint;
alter table public.app_updates add column if not exists storage_path text;
alter table public.app_updates add column if not exists sha256 text;
alter table public.app_updates add column if not exists created_by uuid references public.profiles(id) on delete set null;
alter table public.app_updates add column if not exists updated_at timestamptz not null default now();
alter table public.app_updates add column if not exists published_at timestamptz;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'app_updates_version_code_positive'
      and conrelid = 'public.app_updates'::regclass
  ) then
    alter table public.app_updates
      add constraint app_updates_version_code_positive check (version_code > 0);
  end if;
  if not exists (
    select 1 from pg_constraint
    where conname = 'app_updates_min_version_valid'
      and conrelid = 'public.app_updates'::regclass
  ) then
    alter table public.app_updates
      add constraint app_updates_min_version_valid check (min_version_code > 0 and min_version_code <= version_code);
  end if;
  if not exists (
    select 1 from pg_constraint
    where conname = 'app_updates_channel_valid'
      and conrelid = 'public.app_updates'::regclass
  ) then
    alter table public.app_updates
      add constraint app_updates_channel_valid check (channel in ('stable', 'beta'));
  end if;
  if not exists (
    select 1 from pg_constraint
    where conname = 'app_updates_rollout_valid'
      and conrelid = 'public.app_updates'::regclass
  ) then
    alter table public.app_updates
      add constraint app_updates_rollout_valid check (rollout_percent between 0 and 100);
  end if;
  if not exists (
    select 1 from pg_constraint
    where conname = 'app_updates_file_size_valid'
      and conrelid = 'public.app_updates'::regclass
  ) then
    alter table public.app_updates
      add constraint app_updates_file_size_valid check (file_size is null or file_size >= 0);
  end if;
end
$$;

create unique index if not exists app_updates_published_channel_version_uidx
  on public.app_updates (channel, version_code)
  where is_published = true;
create index if not exists app_updates_created_at_idx
  on public.app_updates (created_at desc, id desc);

drop policy if exists "published updates are public" on public.app_updates;
create policy "published updates are public"
  on public.app_updates
  for select
  to anon, authenticated
  using (is_published = true and channel = 'stable');

create table if not exists public.app_announcements (
  id bigint generated by default as identity primary key,
  title text not null,
  body text not null,
  level text not null default 'info'
    check (level in ('info', 'success', 'warning', 'critical')),
  target_min_version integer,
  target_max_version integer,
  is_published boolean not null default false,
  starts_at timestamptz,
  ends_at timestamptz,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  published_at timestamptz,
  constraint app_announcements_version_range check (
    (target_min_version is null or target_min_version > 0)
    and (target_max_version is null or target_max_version > 0)
    and (target_min_version is null or target_max_version is null or target_min_version <= target_max_version)
  ),
  constraint app_announcements_time_range check (
    starts_at is null or ends_at is null or starts_at < ends_at
  )
);

alter table public.app_announcements enable row level security;
revoke all on public.app_announcements from anon, authenticated;
grant select on public.app_announcements to anon, authenticated;

drop policy if exists "published announcements are public" on public.app_announcements;
create policy "published announcements are public"
  on public.app_announcements
  for select
  to anon, authenticated
  using (
    is_published = true
    and (starts_at is null or starts_at <= now())
    and (ends_at is null or ends_at > now())
  );

create index if not exists app_announcements_published_window_idx
  on public.app_announcements (starts_at, ends_at, created_at desc)
  where is_published = true;
create index if not exists app_announcements_created_at_idx
  on public.app_announcements (created_at desc, id desc);

alter table public.admin_audit_logs add column if not exists resource_type text;
alter table public.admin_audit_logs add column if not exists resource_id text;
alter table public.admin_audit_logs drop constraint if exists admin_audit_logs_action_check;
alter table public.admin_audit_logs
  add constraint admin_audit_logs_action_check check (
    action in (
      'ban', 'unban', 'delete',
      'release_create', 'release_update', 'release_publish', 'release_unpublish', 'release_delete',
      'announcement_create', 'announcement_update', 'announcement_publish', 'announcement_unpublish', 'announcement_delete'
    )
  );
create index if not exists admin_audit_logs_resource_idx
  on public.admin_audit_logs (resource_type, resource_id, created_at desc);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'app-releases',
  'app-releases',
  true,
  209715200,
  array['application/vnd.android.package-archive', 'application/octet-stream']::text[]
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "jianbox admins read release objects" on storage.objects;
create policy "jianbox admins read release objects"
  on storage.objects for select to authenticated
  using (bucket_id = 'app-releases' and (select private.jianbox_is_admin()));

drop policy if exists "jianbox admins upload release objects" on storage.objects;
create policy "jianbox admins upload release objects"
  on storage.objects for insert to authenticated
  with check (bucket_id = 'app-releases' and (select private.jianbox_is_admin()));

drop policy if exists "jianbox admins update release objects" on storage.objects;
create policy "jianbox admins update release objects"
  on storage.objects for update to authenticated
  using (bucket_id = 'app-releases' and (select private.jianbox_is_admin()))
  with check (bucket_id = 'app-releases' and (select private.jianbox_is_admin()));

drop policy if exists "jianbox admins delete release objects" on storage.objects;
create policy "jianbox admins delete release objects"
  on storage.objects for delete to authenticated
  using (bucket_id = 'app-releases' and (select private.jianbox_is_admin()));
